# Generated by Django 3.2.3 on 2021-05-26 15:28

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64)),
            ],
        ),
        migrations.CreateModel(
            name='Institution',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128)),
                ('description', models.TextField()),
                ('institution_type', models.CharField(choices=[('FUND', 'Fundacja'), ('NGOV', 'Organizacja pozarządowa'), ('CHAR', 'Zbiórka lokalna')], default='FUND', max_length=4)),
            ],
        ),
    ]
