# Generated by Django 3.2.3 on 2021-05-26 15:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sharegood', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='institution',
            name='categories',
            field=models.ManyToManyField(to='sharegood.Category'),
        ),
    ]
